services:
  api:
    container_name: db-shavira-fastapi
    build: .
    command: sh -c "uvicorn api.api:app --host=0.0.0.0 --port 3001 --workers 8"
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - .:/app
