services:
  api:
    container_name: db-shavira-fastapi
    build: .
    command: sh -c "uvicorn api:app --host=0.0.0.0 --port 3000 --workers 8"
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
